FROM ubuntu:24.04

RUN apt-get update
RUN apt-get install -y python3.10
RUN apt-get install -y openjdk-8-jre
RUN apt-get install -y zip
RUN apt-get install -y unzip
RUN apt-get install -y curl
# RUN curl -s "https://get.sdkman.io" | bash
# RUN export SDKMAN_DIR="$HOME/.sdkman" && bash -c "source $HOME/.sdkman/bin/sdkman-init.sh" && sdk install -y kotlin
# RUN apt install -y kotlin
RUN apt-get install -y snapd
# RUN systemctl start snapd
# RUN snap refresh
# RUN snap install kotlin --classic
#RUN sdk install gradle
